#!/bin/sh

boh_help() {
    printf "Usage: boh COMMAND [arg...]\n"
    printf "\nTransform a bounch of markdown files into html\n"
    printf "\nCommands:\n"
    printf "\tnew\tInitialize a dir with basic tpl\n"
    printf "\tbuild\tBuild the things\n"
    printf "\tserve\tStart python simple httpd in teh dir\n"
}

boh_new() {
    mkdir _site _assets _templates
    cat <<EOF > _templates/page.tpl
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>\$title</title>
  </head>
  <body>
      \$body
  </body>
</html>
EOF
}

boh_serve() {
    cd _site
    python2 -m SimpleHTTPServer
}

boh_check() {
    if [ ! -d "_templates" ];then
	>&2 echo "'_templates' directory not found. Maybe you should 'boh new'"
	exit 1
    fi
    type markdown &> /dev/null || {
	>&2 echo "'markdown' is not installed"
	exit 1
    }
    type envsubst &> /dev/null || {
	>&2 echo "'envsubst' is not installed, install 'gettext' package"
	exit 1
    }
}

# Parse the yaml frontmatter and returns a string ready for eval
# First sed extract the frontmatter
# Second sed removes frontmatter's delimiter
# Third sed transform yaml in shell evaluable code (lol: asd -> lol="asd")
# Kudos to stackoverflow users for this magic

parse_frontmatter(){
    frontmatter=`cat $1 | sed -n '1{/^---/{:a N;/\n---/!ba;p}}' | sed '1d;$d' | sed -e 's/:[^:\/\/]/="/g;s/$/"/g;s/ *=/=/g'`
    echo $frontmatter
}

boh_build() {
    echo "Building all the things..."
    for file in `find . -type f -name "*.md"`; do
	template="page"
	title=`echo $file | rev | cut -d / -f 1 | rev | sed s/.md//`
	# sed removes the yaml frontmatter
	body=`cat $file | sed '1{/^---/{:a N;/\n---/!ba;d}}' | markdown`
	newpath="./_site/"`echo $file | rev | cut -d . -f 2 | rev`".html"
	frontmatter=`parse_frontmatter $file`
	if [  "$frontmatter" ];then
	    eval $frontmatter
	fi
	mkdir -p "${newpath%/*}"
	export title body
	envsubst < "_templates/$template.tpl" > "$newpath"
	unset title body
    done
    if [ -d "_assets" ];then
	cp -R _assets/* _site/
    fi
    echo "Yay!"
}

case $1 in
    "build")
	boh_check
	boh_build
	;;
    "new")
	boh_new
	;;
    "serve")
	boh_serve
	;;
    *)
	boh_help
	;;
esac
